export interface Category {
  name: string;
  wikipediaCategory: string;
  entityType: string;
}

export const CATEGORIES: Category[] = [
  {
    name: "Historical Figures",
    wikipediaCategory: "Category:Historical_figures",
    entityType: "historical figure",
  },
  {
    name: "NFL Athletes",
    wikipediaCategory: "Category:American_football_players",
    entityType: "NFL player",
  },
  {
    name: "Countries",
    wikipediaCategory: "Category:Countries",
    entityType: "country",
  },
  {
    name: "Music Groups (80s)",
    wikipediaCategory: "Category:Musical_groups_established_in_the_1980s",
    entityType: "music group from the 1980s",
  },
  {
    name: "US Presidents",
    wikipediaCategory: "Category:Presidents_of_the_United_States",
    entityType: "US President",
  },
  {
    name: "Scientists",
    wikipediaCategory: "Category:Scientists",
    entityType: "scientist",
  },
  {
    name: "World Cities",
    wikipediaCategory: "Category:Cities",
    entityType: "city",
  },
  {
    name: "Olympic Athletes",
    wikipediaCategory: "Category:Olympic_athletes",
    entityType: "Olympic athlete",
  },
  {
    name: "Classic Films",
    wikipediaCategory: "Category:American_films",
    entityType: "classic film",
  },
  {
    name: "Animals",
    wikipediaCategory: "Category:Animals",
    entityType: "animal species",
  },
];

// Hand-curated entity lists for reliable Wikipedia coverage.
// These are used instead of (or alongside) scraped category pages.
export const CURATED_ENTITIES: Record<string, string[]> = {
  "US Presidents": [
    "George Washington",
    "Abraham Lincoln",
    "Thomas Jefferson",
    "Franklin D. Roosevelt",
    "Theodore Roosevelt",
    "John F. Kennedy",
    "Dwight D. Eisenhower",
    "Harry S. Truman",
    "Lyndon B. Johnson",
    "James K. Polk",
    "Andrew Jackson",
    "James Madison",
    "John Adams",
    "Ulysses S. Grant",
    "Woodrow Wilson",
    "Ronald Reagan",
    "Richard Nixon",
    "Bill Clinton",
    "Barack Obama",
    "Jimmy Carter",
  ],
  "Historical Figures": [
    "Napoleon Bonaparte",
    "Julius Caesar",
    "Cleopatra",
    "Alexander the Great",
    "Genghis Khan",
    "Leonardo da Vinci",
    "Galileo Galilei",
    "Isaac Newton",
    "Marie Curie",
    "Nikola Tesla",
    "Charles Darwin",
    "Karl Marx",
    "Sigmund Freud",
    "Winston Churchill",
    "Mahatma Gandhi",
    "Martin Luther King Jr.",
    "Nelson Mandela",
    "Joan of Arc",
    "Catherine the Great",
    "Elizabeth I of England",
  ],
  Countries: [
    "France",
    "Japan",
    "Brazil",
    "Australia",
    "Egypt",
    "India",
    "Mexico",
    "Canada",
    "Germany",
    "South Africa",
    "Argentina",
    "Italy",
    "Spain",
    "China",
    "Russia",
    "New Zealand",
    "Greece",
    "Turkey",
    "Thailand",
    "Nigeria",
  ],
  "World Cities": [
    "Tokyo",
    "Paris",
    "New York City",
    "London",
    "Sydney",
    "Rome",
    "Cairo",
    "Mumbai",
    "Rio de Janeiro",
    "Istanbul",
    "Barcelona",
    "Buenos Aires",
    "Seoul",
    "Amsterdam",
    "Vienna",
    "Bangkok",
    "Mexico City",
    "Dubai",
    "Singapore",
    "Nairobi",
  ],
  Scientists: [
    "Albert Einstein",
    "Isaac Newton",
    "Charles Darwin",
    "Marie Curie",
    "Nikola Tesla",
    "Stephen Hawking",
    "Richard Feynman",
    "Niels Bohr",
    "Max Planck",
    "Louis Pasteur",
    "Gregor Mendel",
    "Carl Sagan",
    "Jane Goodall",
    "Neil deGrasse Tyson",
    "Carl Linnaeus",
    "Ada Lovelace",
    "Alan Turing",
    "Rosalind Franklin",
    "Edwin Hubble",
    "Enrico Fermi",
  ],
};
